### ISSUE TITLE
Missing dependency on package FGA

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#117] opened 2017-12-12 12:37 UTC
CAP uses the global function `BoundPositions` which is installed by the package FGA. However, CAP has no dependency on FGA. Thus, if CAP is loaded without loading FGA first, the following warnings appear:

```
Syntax warning: unbound global variable in /xxxxxx/CAP_project/CAP/gap/ToolsForCategories.gi line 747
        Print( String( Length( BoundPositions( current_cache!.value ) ) ), " objects stored\n" );
                                             ^
Syntax warning: unbound global variable in /xxxxxx/CAP_project/CAP/gap/ToolsForCategories.gi line 787
        Append( current_list, [ current_cache!.hit_counter, current_cache!.miss_counter, Length( BoundPositions( current_cache!.value ) ) ] );
                                                                                                               ^
```

The corresponding code references are:

https://github.com/homalg-project/CAP_project/blob/1ad16e280feab245d6ceaa323c9eecbdf5326ba9/CAP/gap/ToolsForCategories.gi#L747

https://github.com/homalg-project/CAP_project/blob/1ad16e280feab245d6ceaa323c9eecbdf5326ba9/CAP/gap/ToolsForCategories.gi#L787

**Comment by sebasguts** [comment] 2017-12-12 12:43
Thanks for pointing this out.

@sebastianpos This is a one-line function. Should we really introduce a dependency here or have our own function? The function that replaces this is
```
list -> Filtered( [ 1 .. Length( list ) ], i -> IsBound( list[ i ] ) );
```

**Comment by sebastianpos** [comment] 2017-12-12 12:54
No, a dependency from FGA seems implausible.
We should either provide our own function
or ask for moving this function.

**Comment by sebasguts** [comment] 2017-12-13 08:45
I provided a PR to the GAP repository: https://github.com/gap-system/gap/pull/2021

Once it is merged, we can replace `BoundPositions( list )` by `PositionsProperty( list, ReturnTrue )`.

**Comment by alex-konovalov** [comment] 2018-01-14 16:41
Thanks @sebasguts but unfortunately it does not solve problems for GAP 4.8 releases. The problem was not visible in regression tests before, since FGA was loaded before CAP. But after some recent package updates the order in which packages are loaded changed, and now I can see the error message about unbound global variable in the test logs. I will try to find which package(s) are responsible for that and revert those packages to their prior versions included in GAP 4.8.9 (which did not have that problem). Alternatively, an urgent release of CAP with the documented dependency may be more helpful.

**Comment by alex-konovalov** [comment] 2018-01-14 22:07
My previous analysis was incorrect - I've assumed that the error report refers to the current release of CAP, not to its development version. So, the problem did not appear in GAP 4.8.9 distribution because CAP version there did not use `BoundPositions` at all. Its use was introduced in CAP-2017.12.30, and hence the new CAP release breaks GAP regression tests and can not be included in GAP 4.8.10 distribution.

I've now specified that GAP 4.8.10 distribution should use stable releases of packages from the CAP project in https://github.com/gap-system/gap-distribution/commit/a5e71a190fe45d8e5f91b4970c818e40a04d5ab3. There is no need for an urgent release then, just fixing this in due course by switching to `PositionsProperty` in GAP 4.9 could be fine.

**Comment by sebasguts** [comment] 2018-01-22 09:02
@alex-konovalov okay. Since the commit defining `PositionsProperty` is not yet in the lastest release GAP, I will not yet make this fix in the master branch. Once we come close to `4.9`, I will update CAP accordingly. I will leave this issue open until then.

**Comment by alex-konovalov** [comment] 2018-07-06 21:42
This is a reminder that I still can not include latest releases of the CAP project in GAP 4.9 distribution because of this issue (see https://github.com/gap-system/gap/wiki/Package-updates-status - am using their stable versions instead).

**Comment by sebasguts** [comment] 2018-07-07 11:16
Thanks for the reminder. I just merged the corresponding PR and will make a release this weekend.

**Closed** 2018-07-07 11:16 UTC

**Comment by alex-konovalov** [comment] 2018-08-17 10:17
@sebasguts Did the release happen? I don't see any new versions of CAP & friends being picked up.
