### ISSUE TITLE
Unexpected behaviour when installing WithGiven operations

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#455] opened 2019-12-12 16:36 UTC
When installing a WithGiven operation, the corresponding without given operation is also installed automatically: https://github.com/homalg-project/CAP_project/blob/master/CAP/gap/InstallAdds.gi#L513

and added as a primitive operation: https://github.com/homalg-project/CAP_project/blob/master/CAP/gap/InstallAdds.gi#L507

Thus, if one only installs for example `KernelEmbeddingWithGivenKernelObject`, afterwards `CanCompute( cat, "KernelObject" )` returns true, but of course calling `KernelObject` leads to an infinite recursion via `KernelObject( alpha ) = Source( KernelEmbedding( alpha ) ) = KernelEmbeddingWithGivenKernelObject( alpha, KernelObject( alpha ) )`.

I tried to add a warning for this in #454, but this failed because even if the object function is not primitively installed it might be derived in a way not leading to an infinite recursion.

I guess the proper solution for this would be to remove the code in https://github.com/homalg-project/CAP_project/blob/master/CAP/gap/InstallAdds.gi#L513 and instead use the derivation mechanism to derive `KernelEmbedding` from `KernelEmbeddingWithGivenKernelObject` and `KernelObject`. But I am not sure about other implications the removal might have.

Do you have any ideas/suggestions for improving the behaviour or adding a warning?

Note: the without given operation is not added to the list of primitively installed functions: https://github.com/homalg-project/CAP_project/blob/master/CAP/gap/InstallAdds.gi#L509 So at least this can be tested.

**Comment by zickgraf** [comment] 2019-12-13 12:26
I have started an attempt to use the derivation mechanism to derive the with/without given pairs: https://github.com/zickgraf/CAP_project/commit/6ee49bd74e3b92441ae6fea273324e9533430ad1 The logic detecting the pairs and the redirect handling is still a bit hacky but the tests run fine and removing the `pair_func` stuff removes a lot of complexity from the add installation.  But of course I might be unaware of some side effects caused by this.

Would you accept a PR with an improved version of the above commit or would you rather not touch this code?

**Comment by sebastianpos** [comment] 2019-12-16 13:23
Okay, let me start this non-trivial topic with a description of the intended behaviour of a basic operation `F` and `FWithGivenX`:

- The idea is that one should not think of `F` and `FWithGivenX` as 2 different basic operations, but only as a single basic operation (namely `F`). `AddFWithGivenX` should be thought of as a convenient function for `AddF` in which the user also has `X` available without the need of creating `X` within his function on his own, but of course with the restriction that the user also needs to call `AddX` somewhere within his creation of his category.

On a technical level, this unity of `F` and `FWithGivenX` is realized by the `pair_func` mechanism to which you pointed, and by the usage of `AddWithGivenDerivationPairToCAP` for the installation of derivations of such paired functions. 

Unfortunately, this technical realization does not faithfully reflect the idea above, namely that `AddFWithGivenX` should only be seen as a convenience for `AddF`. The main reason for its current realization is that the implementation of `WithGiven`-functions was already done before we came up with CAP's concept of equality and the resulting specifications.

In the long run, I would like to aim for a more faithful realization of this idea.

Okay, now to your concrete problem:

I like the idea that as a first step, there should be warnings that hint to the intended behaviour above:
1) there should be a warning if the user calls both `AddFWithGivenX` and `AddF`, since only the last call counts. I think inserting such a warning will hint to unnecessary code in CAP.
2) The idea of PR #454 is fine. If the user provides `AddFWithGivenX` without providing `AddX`, there should be a warning, regardless of the fact that the system might nevertheless be able to create `X` correctly.

For providing such warnings we need to know which functions are really given by the user, and not provided by the system. Being marked as `primitive` is not good enough as a check, as you have encountered. Maybe it's an idea to mark those functions that were installed by the system. That would imply to mark:
- derivations
- the complementary pair function

Would you like to provide such a marking?

Concerning your idea of using the derivation mechanism to get rid of the `pair_func` mechanism: since it seems to treat `F` and `FWithGivenX` again as 2 separate entities, I would rather not like to follow it.

**Comment by zickgraf** [comment] 2019-12-19 11:46
Thanks for your thorough reply!

> `AddFWithGivenX` should be thought of as a convenient function for `AddF` in which the user also has `X` available without the need of creating `X` within his function on his own

From a discussion with @mohamed-barakat I understood that besides convenience this can also be used for performance reasons. The example was the computation of the kernel embedding in left presentations: computing the matrix defining the morphism only needs one syzygy computation, but computing the presentation of the kernel object needs an additional one. So if I already know the kernel object from another computation, I can pass it to `KernelEmbeddingWithGivenKernelObject` directly. Is this also a main purpose of the `WithGiven` functions or rather a side effect?

> there should be a warning if the user calls both `AddFWithGivenX` and `AddF`, since only the last call counts.

I'm not sure what you mean with "only the last call counts". In the given setting, when calling `F` when `X` is not cached, the function passed to `AddF` will be called. When calling `F` when `X` is already cashed, or when calling `FWithGivenX`, the function passed to `AddFWithGivenX` will be called. (I have attached my test code below).

> The idea of PR #454 is fine. If the user provides `AddFWithGivenX` without providing AddX, there should be a warning, regardless of the fact that the system might nevertheless be able to create X correctly.
> For providing such warnings we need to know which functions are really given by the user, and not provided by the system.

I think #454 already implements this (modulo the special case mentioned in the description): it uses `ListPrimitivelyInstalledOperationsOfCategory`, which is explicitly not populated with the complementary pair functions: https://github.com/homalg-project/CAP_project/blob/master/CAP/gap/InstallAdds.gi#L509 The CI currently fails because warnings are triggered for `LeftPresentations`, where `CokernelProjection` and `CokernelColiftWithGivenCokernelObject` are primitively installed. So `CokernelObject` can be derived from `CokernelProjection` and used to compute `CokernelColiftWithGivenCokernelObject`. If this situation should indeed trigger a warning, I can of course update #454 by suppressing the warning for `LeftPresentations` or by implementing `CokernelObject`.

One more thing: I probably should have already mentioned before, why I am interested in this in the first place: action categories installs `CokernelProjectionWithGivenCokernelObject` but not `CokernelProjection` if the underlying category does not have a `Colift` operation. If I understand this correctly, this is mathematically correct because the only problem is finding a structure morphism for the cokernel object. If one follows the idea of regarding `F` and `FWithGivenX` as a single basic operation, one could not install `CokernelProjectionWithGivenCokernelObject` in this case.



My test case:
```
LoadPackage( "CAP" );

cat := CreateCapCategory( );
myobj := SymmetricGroup( 3 );
AddObject( cat, myobj );
mymor := GroupHomomorphismByImages( myobj, myobj );
AddMorphism( cat, mymor );

AddKernelObject( cat, function( a )
    
    Display( "via KernelObject" );
    
    return myobj;
    
end );

AddKernelEmbeddingWithGivenKernelObject( cat, function( a, b )
    
    Display( "via KernelEmbeddingWithGivenKernelObject" );
    
    return mymor;
end );

AddKernelEmbedding( cat, function( a )
    
    Display( "via KernelEmbedding" );
    
    return mymor;
end );

# Display( "computing KernelObject" );
# KernelObject( mymor );
Display( "computing KernelEmbedding" );
KernelEmbedding( mymor );
Display( "computing KernelEmbeddingWithGivenKernelObject" );
KernelEmbeddingWithGivenKernelObject( mymor, myobj );
```

The result is:
```
computing KernelEmbedding
via KernelEmbedding
computing KernelEmbeddingWithGivenKernelObject
via KernelEmbeddingWithGivenKernelObject
```

When uncommenting the two commented lines, the result is:
```
computing KernelObject
via KernelObject
computing KernelEmbedding
via KernelEmbeddingWithGivenKernelObject
computing KernelEmbeddingWithGivenKernelObject
```
(The last `KernelEmbeddingWithGivenKernelObject` is already cashed in this case).

**Closed** 2020-04-24 13:07 UTC
